### ISSUE TITLE
after clicking synchronize: foreach() argument must be of type array|object, string given

### ISSUE THREAD

**Issue by sahapranta** [musa11971/filament-translation-manager#4] opened 2023-04-17 04:39 UTC
ErrorException  [PHP 8.1.2], Windows 10 Machine
# foreach() argument must be of type array|object, string given

```php
// folder\vendor\musa11971\filament-translation-manager\src\Helpers\TranslationScanner.php : line51

private function traverseArray($array, &$seenCombinations, &$allGroupsAndKeys, $groupName, $parentKey = null): void
    {
        foreach ($array as $key => $value) {
```

**Comment by Solunsky** [comment] 2023-04-17 13:33
See, have promblem, but have mini-solution

https://github.com/musa11971/filament-translation-manager/issues/2#issuecomment-1510314975

**Comment by sahapranta** [comment] 2023-04-17 15:22
@Solunsky 
```php
$name = explode(DIRECTORY_SEPARATOR , $name);
unset($name[0]);
$name = implode(DIRECTORY_SEPARATOR, $name);
```
This will be more convenient but changing inside vendor is not a good idea. Because there will be automatic deployment on server, I cannot do it every time.

**Comment by musa11971** [comment] 2023-04-17 15:23
Duplicate of #2 - fixed in https://github.com/musa11971/filament-translation-manager/releases/tag/1.0.4

**Closed by musa11971** 2023-04-17 15:23 UTC
